FROM openjdk:8-jdk-alpine
ARG JAR_FILE
ENV SPRING_RABBITMQ_HOST="192.168.99.100"
ENV SPRING_RABBITMQ_PORT=5672
ENV SPRING_RABBITMQ_USERNAME="guest"
ENV SPRING_RABBITMQ_PASSWORD="guest"
ENV PUBLISH_FIXEDDELAY_IN_MILLISECONDS=1000
ENV PROCESSING_FIXEDDELAY_IN_MILLISECONDS=10000
ENV SPRING_DATA_MONGODB_DATABASE="streaming_analytics"
ENV SPRING_DATA_MONGODB_HOST="192.168.99.100"
ENV SPRING_DATA_MONGODB_PORT=27017
ENV SPRING_DATA_MONGODB_USERNAME="private"
ENV SPRING_DATA_MONGODB_PASSWORD="secret"
ENV LOGGING_LEVEL_ROOT=INFO

COPY ${JAR_FILE} app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "/app.jar"]